apiVersion: v1
kind: Service
metadata:
  labels:
    app: openshift-route-controller-manager
  name: openshift-route-controller-manager
  namespace: HCP_NAMESPACE
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app: openshift-route-controller-manager
  type: ClusterIP
