---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.15.0
  name: clustersizingconfigurations.scheduling.hypershift.openshift.io
spec:
  group: scheduling.hypershift.openshift.io
  names:
    kind: ClusterSizingConfiguration
    listKind: ClusterSizingConfigurationList
    plural: clustersizingconfigurations
    shortNames:
    - csc
    - cscs
    singular: clustersizingconfiguration
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: |-
          ClusterSizingConfiguration defines the desired state of ClusterSizingConfiguration.
          Configuration options here allow management cluster administrators to define sizing classes for hosted clusters and
          how the system should adapt hosted cluster functionality based on size.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: ClusterSizingConfigurationSpec defines the desired state
              of ClusterSizingConfiguration
            properties:
              concurrency:
                description: |-
                  Concurrency defines the bounds of allowed behavior for clusters transitioning between sizes.
                  Transitions will require that request-serving pods be re-scheduled between nodes, so each
                  transition incurs a small user-facing cost as well as a cost to the management cluster. Use
                  the concurrency configuration options to manage how many transitions can be occurring.
                  These limits do not apply to new clusters entering the fleet.
                  If unset, a sensible default will be provided.
                properties:
                  limit:
                    default: 5
                    description: Limit is the maximum allowed number of cluster size
                      transitions during the sliding window.
                    format: int32
                    minimum: 1
                    type: integer
                  slidingWindow:
                    default: 10m
                    description: SlidingWindow is the window over which the concurrency
                      bound is enforced.
                    pattern: ^([0-9]+(\.[0-9]+)?(s|m|h))+$
                    type: string
                required:
                - limit
                - slidingWindow
                type: object
              nonRequestServingNodesBufferPerZone:
                anyOf:
                - type: integer
                - type: string
                description: |-
                  NonRequestServingNodesBufferPerZone is the number of extra nodes to allocate for non request serving
                  workloads per zone.
                pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                x-kubernetes-int-or-string: true
              sizes:
                description: |-
                  Sizes holds the different t-shirt size classes into which guest clusters will be sorted.
                  Each size class applies to guest clusters using node count criteria; it is required that
                  the entire interval between [0,+inf) be covered by the set of sizes provided here.
                items:
                  description: SizeConfiguration holds options for clusters of a given
                    size.
                  properties:
                    criteria:
                      description: Criteria defines the node count range for clusters
                        to fall into this t-shirt size class.
                      properties:
                        from:
                          description: From is the inclusive lower limit to node count
                            for a cluster to be considered a particular size.
                          format: int32
                          minimum: 0
                          type: integer
                        to:
                          description: |-
                            To is the inclusive upper limit to node count for a cluster to be considered a particular size.
                            If unset, this size class will match clusters of all sizes greater than the lower limit.
                          format: int32
                          minimum: 0
                          type: integer
                      required:
                      - from
                      type: object
                      x-kubernetes-validations:
                      - message: lower limit must be less than or equal to the upper
                          limit
                        rule: '!has(self.to) || self.from <= self.to'
                    effects:
                      description: Effects define the effects on a cluster being considered
                        part of this t-shirt size class.
                      properties:
                        APICriticalPriorityClassName:
                          description: |-
                            APICriticalPriorityClassName is the priority class for pods in the API request serving path.
                            This includes Kube API Server, OpenShift APIServer, etc.
                          type: string
                        controlPlanePriorityClassName:
                          description: ControlPlanePriorityClassName is the priority
                            class to use for most control plane pods
                          type: string
                        etcdPriorityClassName:
                          description: EtcdPriorityClassName is the priority class
                            to use for etcd pods
                          type: string
                        kasGoMemLimit:
                          description: |-
                            KASGoMemLimit is the value to set for the $GOMEMLIMIT of the Kube APIServer container
                            Expected format is a number followed by a unit (B, KiB, MiB, GiB, TiB). See the Go runtime library for more
                            information on the format - https://pkg.go.dev/runtime#hdr-Environment_Variables.
                          maxLength: 20
                          pattern: ^\d+(B|KiB|MiB|GiB|TiB)?$
                          type: string
                        machineHealthCheckTimeout:
                          description: |-
                            MachineHealthCheckTimeout specifies an optional timeout for machinehealthchecks created
                            for HostedClusters with this specific size.
                          type: string
                        maximumMutatingRequestsInflight:
                          description: MaximumMutatingRequestsInflight specifies the
                            maximum mutating requests in flight for Kube APIServer
                          type: integer
                        maximumRequestsInflight:
                          description: MaximumRequestsInFlight specifies the maximum
                            requests in flight for Kube APIServer
                          type: integer
                        resourceRequests:
                          description: ResourceRequests allows specifying resource
                            requests for control plane pods.
                          items:
                            properties:
                              containerName:
                                description: ContainerName is the name of the container
                                  to which the resource request applies.
                                type: string
                              cpu:
                                anyOf:
                                - type: integer
                                - type: string
                                description: CPU is the amount of CPU to request for
                                  the container.
                                pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                                x-kubernetes-int-or-string: true
                              deploymentName:
                                description: DeploymentName is the name of the deployment
                                  to which the resource request applies.
                                type: string
                              memory:
                                anyOf:
                                - type: integer
                                - type: string
                                description: Memory is the amount of memory to request
                                  for the container.
                                pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                                x-kubernetes-int-or-string: true
                            required:
                            - containerName
                            - deploymentName
                            type: object
                          type: array
                      type: object
                    management:
                      description: Management configures the management aspects of
                        this size class on the management plane.
                      properties:
                        nonRequestServingNodesPerZone:
                          anyOf:
                          - type: integer
                          - type: string
                          description: |-
                            NonRequestServingNodesPerZone is the number of nodes to allocate for non request serving workloads
                            per HostedCluster. This will likely be a fraction of a node (ie. 0.2) to allow 5 HostedClusters in
                            a single node. The total number of nodes needed per HostedCluster is this number multiplied by 3
                            (number of zones).
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        placeholders:
                          description: |-
                            Placeholders configures the number of dummy workloads that will be scheduled irrespective of
                            HostedClusters in order to keep a set of nodes ready to accept new cluster creation and scheduling.
                          minimum: 0
                          type: integer
                      type: object
                    name:
                      description: Name is the t-shirt size name.
                      type: string
                  required:
                  - criteria
                  - name
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - name
                x-kubernetes-list-type: map
                x-kubernetes-validations:
                - message: exactly one size class must have a lower limit of zero
                  rule: self.exists_one(i, i.criteria.from == 0)
                - message: exactly one size class must have no upper limit
                  rule: self.exists_one(i, !has(i.criteria.to))
              transitionDelay:
                description: |-
                  TransitionDelay configures how quickly the system reacts to clusters transitioning between size classes.
                  It may be advantageous, for instance, to have a near-instant scale-down for clusters that begin to
                  use fewer resources, but allow for some lag on scale-up to ensure that the use is sustained before
                  incurring the larger cost for scale-up.
                properties:
                  decrease:
                    default: 10m
                    description: |-
                      Decrease defines the minimum period of time to wait between a cluster's size decreasing and
                      the t-shirt size assigned to it being updated to reflect the new size.
                    pattern: ^([0-9]+(\.[0-9]+)?(s|m|h))+$
                    type: string
                  increase:
                    default: 30s
                    description: |-
                      Increase defines the minimum period of time to wait between a cluster's size increasing and
                      the t-shirt size assigned to it being updated to reflect the new size.
                    pattern: ^([0-9]+(\.[0-9]+)?(s|m|h))+$
                    type: string
                type: object
            required:
            - sizes
            type: object
          status:
            description: ClusterSizingConfigurationStatus defines the observed state
              of ClusterSizingConfiguration
            properties:
              conditions:
                description: Conditions contain details about the various aspects
                  of cluster sizing.
                items:
                  description: Condition contains details for one aspect of the current
                    state of this API Resource.
                  properties:
                    lastTransitionTime:
                      description: |-
                        lastTransitionTime is the last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        message is a human readable message indicating details about the transition.
                        This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: |-
                        observedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: |-
                        reason contains a programmatic identifier indicating the reason for the condition's last transition.
                        Producers of specific condition types may define expected values and meanings for this field,
                        and whether the values are considered a guaranteed API.
                        The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
            type: object
        type: object
        x-kubernetes-validations:
        - message: exactly one configuration may exist and must be named 'cluster'
          rule: self.metadata.name == 'cluster'
    served: true
    storage: true
    subresources:
      status: {}
