# https://github.com/openshift/cluster-kube-controller-manager-operator/blob/64b4c1ba/bindata/assets/kube-controller-manager/recycler-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: recycler-config
data:
  recycler-pod.yaml: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: recycler-pod
      namespace: openshift-infra
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
    spec:
      activeDeadlineSeconds: 60
      restartPolicy: Never
      serviceAccountName: pv-recycler-controller
      containers:
        - name: recycler-container
          image: {{.tools_image}}
          command:
          - "/bin/bash"
          args:
          - "-c"
          - "test -e /scrub && rm -rf /scrub/..?* /scrub/.[!.]* /scrub/*  && test -z \"$(ls -A /scrub)\" || exit 1"
          volumeMounts:
            - mountPath: /scrub
              name: vol
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 0
          priorityClassName: openshift-user-critical
          resources:
            requests:
              memory: 50Mi
              cpu: 10m
      volumes:
        - name: vol
