apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-controller-manager
  name: kube-controller-manager
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: client
    port: 10257
    protocol: TCP
    targetPort: client
  selector:
    app: kube-controller-manager
  sessionAffinity: None
  type: ClusterIP
