apiVersion: v1
kind: Service
metadata:
  name: endpoint-resolver
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 9444
  selector:
    app: endpoint-resolver
  type: ClusterIP
