apiVersion: apps/v1
kind: Deployment
metadata:
  name: karpenter
  namespace: HCP_NAMESPACE
  labels:
    app: karpenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karpenter
  template:
    metadata:
      labels:
        app: karpenter
    spec:
      serviceAccountName: karpenter
      terminationGracePeriodSeconds: 10
      containers:
        - name: karpenter
          image: aws-karpenter-provider-aws # replaced by payload
          args:
            - "--log-level=debug"
          env:
            - name: KUBECONFIG
              value: "/mnt/kubeconfig/target-kubeconfig"
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DISABLE_WEBHOOK
              value: "true"
            - name: DISABLE_LEADER_ELECTION
              value: "true"
            - name: FEATURE_GATES
              value: "Drift=true"
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: "/etc/provider/credentials"
            - name: AWS_SDK_LOAD_CONFIG
              value: "true"
            - name: HEALTH_PROBE_PORT
              value: "8081"
            - name: CLUSTER_ENDPOINT
              value: "https://fake.com"
          ports:
            - name: metrics
              containerPort: 8080
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              memory: "60Mi"
              cpu: "10m"
          volumeMounts:
            - name: target-kubeconfig
              mountPath: "/mnt/kubeconfig"
            - name: provider-creds
              mountPath: "/etc/provider"
            - name: serviceaccount-token
              mountPath: "/var/run/secrets/openshift/serviceaccount"
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
      volumes:
        - name: target-kubeconfig
          secret:
            # secretName: to be replaced by adaptDeployment
            defaultMode: 0640
            items:
              - key: value
                path: target-kubeconfig
        - name: serviceaccount-token
          emptyDir: {}
        - name: provider-creds
          secret:
            secretName: "karpenter-credentials"