apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-tracer
  namespace: hypershift
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admission-tracer
  template:
    metadata:
      labels:
        app: admission-tracer
    spec:
      containers:
      - command:
        - /usr/bin/admission-tracer
        image: quay.io/sjenning/admission-tracer:latest
        imagePullPolicy: Always
        name: admission-tracer
        ports:
        - containerPort: 9443
          name: manager
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
        volumeMounts:
        - mountPath: /var/run/secrets/serving-cert
          name: serving-cert
      priorityClassName: hypershift-operator
      serviceAccountName: operator
      volumes:
      - name: serving-cert
        secret:
          defaultMode: 0640
          secretName: admission-tracer-serving-cert
