apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-storage-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cluster-storage-operator
  template:
    metadata:
      annotations:
        openshift.io/required-scc: restricted-v2
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
      labels:
        app: cluster-storage-operator
        name: cluster-storage-operator
    spec:
      containers:
      - args:
        - start
        - -v=2
        - --terminate-on-files=/var/run/secrets/serving-cert/tls.crt
        - --terminate-on-files=/var/run/secrets/serving-cert/tls.key
        - --guest-kubeconfig=/etc/guest-kubeconfig/kubeconfig
        command:
        - cluster-storage-operator
        - start
        env:
        - name: OPERATOR_IMAGE_VERSION
          value: 0.0.1-snapshot
        - name: OPERAND_IMAGE_VERSION
          value: 0.0.1-snapshot
        - name: AWS_EBS_DRIVER_OPERATOR_IMAGE
          value: quay.io/openshift/origin-aws-ebs-csi-driver-operator:latest
        - name: AWS_EBS_DRIVER_IMAGE
          value: quay.io/openshift/origin-aws-ebs-csi-driver:latest
        - name: GCP_PD_DRIVER_OPERATOR_IMAGE
          value: quay.io/openshift/origin-gcp-pd-csi-driver-operator:latest
        - name: GCP_PD_DRIVER_IMAGE
          value: quay.io/openshift/origin-gcp-pd-csi-driver:latest
        - name: OPENSTACK_CINDER_DRIVER_OPERATOR_IMAGE
          value: quay.io/openshift/origin-openstack-cinder-csi-driver-operator:latest
        - name: OPENSTACK_CINDER_DRIVER_IMAGE
          value: quay.io/openshift/origin-openstack-cinder-csi-driver:latest
        - name: OVIRT_DRIVER_OPERATOR_IMAGE
          value: quay.io/openshift/origin-ovirt-csi-driver-operator:latest
        - name: OVIRT_DRIVER_IMAGE
          value: quay.io/openshift/origin-ovirt-csi-driver:latest
        - name: MANILA_DRIVER_OPERATOR_IMAGE
          value: quay.io/openshift/origin-csi-driver-manila-operator:latest
        - name: MANILA_DRIVER_IMAGE
          value: quay.io/openshift/origin-csi-driver-manila:latest
        - name: MANILA_NFS_DRIVER_IMAGE
          value: quay.io/openshift/origin-csi-driver-nfs:latest
        - name: PROVISIONER_IMAGE
          value: quay.io/openshift/origin-csi-external-provisioner:latest
        - name: ATTACHER_IMAGE
          value: quay.io/openshift/origin-csi-external-attacher:latest
        - name: RESIZER_IMAGE
          value: quay.io/openshift/origin-csi-external-resizer:latest
        - name: SNAPSHOTTER_IMAGE
          value: quay.io/openshift/origin-csi-external-snapshotter:latest
        - name: NODE_DRIVER_REGISTRAR_IMAGE
          value: quay.io/openshift/origin-csi-node-driver-registrar:latest
        - name: LIVENESS_PROBE_IMAGE
          value: quay.io/openshift/origin-csi-livenessprobe:latest
        - name: VSPHERE_PROBLEM_DETECTOR_OPERATOR_IMAGE
          value: quay.io/openshift/origin-vsphere-problem-detector:latest
        - name: AZURE_DISK_DRIVER_OPERATOR_IMAGE
          value: quay.io/openshift/origin-azure-disk-csi-driver-operator:latest
        - name: AZURE_DISK_DRIVER_IMAGE
          value: quay.io/openshift/origin-azure-disk-csi-driver:latest
        - name: AZURE_FILE_DRIVER_OPERATOR_IMAGE
          value: quay.io/openshift/origin-azure-file-csi-driver-operator:latest
        - name: AZURE_FILE_DRIVER_IMAGE
          value: quay.io/openshift/origin-azure-file-csi-driver:latest
        - name: KUBE_RBAC_PROXY_IMAGE
          value: quay.io/openshift/origin-kube-rbac-proxy:latest
        - name: VMWARE_VSPHERE_DRIVER_OPERATOR_IMAGE
          value: quay.io/openshift/origin-vsphere-csi-driver-operator:latest
        - name: VMWARE_VSPHERE_DRIVER_IMAGE
          value: quay.io/openshift/origin-vsphere-csi-driver:latest
        - name: VMWARE_VSPHERE_SYNCER_IMAGE
          value: quay.io/openshift/origin-vsphere-csi-driver-syncer:latest
        - name: CLUSTER_CLOUD_CONTROLLER_MANAGER_OPERATOR_IMAGE
          value: quay.io/openshift/origin-cluster-cloud-controller-manager-operator:latest
        - name: IBM_VPC_BLOCK_DRIVER_OPERATOR_IMAGE
          value: quay.io/openshift/origin-ibm-vpc-block-csi-driver-operator:latest
        - name: IBM_VPC_BLOCK_DRIVER_IMAGE
          value: quay.io/openshift/origin-ibm-vpc-block-csi-driver:latest
        - name: POWERVS_BLOCK_CSI_DRIVER_OPERATOR_IMAGE
          value: quay.io/openshift/origin-powervs-block-csi-driver-operator:latest
        - name: POWERVS_BLOCK_CSI_DRIVER_IMAGE
          value: quay.io/openshift/origin-powervs-block-csi-driver:latest
        - name: HYPERSHIFT_IMAGE
          value: quay.io/openshift/origin-control-plane:latest
        - name: AWS_EBS_DRIVER_CONTROL_PLANE_IMAGE
          value: quay.io/openshift/origin-aws-ebs-csi-driver:latest
        - name: AZURE_DISK_DRIVER_CONTROL_PLANE_IMAGE
          value: quay.io/openshift/origin-azure-disk-csi-driver-operator:latest
        - name: LIVENESS_PROBE_CONTROL_PLANE_IMAGE
          value: quay.io/openshift/origin-csi-livenessprobe:latest
        - name: AZURE_FILE_DRIVER_CONTROL_PLANE_IMAGE
          value: quay.io/openshift/origin-azure-file-csi-driver-operator:latest
        - name: OPENSTACK_CINDER_DRIVER_CONTROL_PLANE_IMAGE
          value: quay.io/openshift/origin-openstack-cinder-csi-driver-operator:latest
        - name: MANILA_DRIVER_CONTROL_PLANE_IMAGE
          value: quay.io/openshift/origin-csi-driver-manila-operator:latest
        - name: KUBE_RBAC_PROXY_CONTROL_PLANE_IMAGE
          value: quay.io/openshift/origin-kube-rbac-proxy:latest
        - name: TOOLS_IMAGE
          value: quay.io/openshift/origin-tools:latest
        - name: VOLUME_DATA_SOURCE_VALIDATOR_IMAGE
          value: quay.io/openshift/origin-volume-data-source-validator:latest
        image: cluster-storage-operator
        imagePullPolicy: IfNotPresent
        name: cluster-storage-operator
        ports:
        - containerPort: 8443
          name: metrics
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /etc/guest-kubeconfig
          name: guest-kubeconfig
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: cluster-storage-operator
      volumes:
      - name: guest-kubeconfig
        secret:
          secretName: service-network-admin-kubeconfig
