site_name: HyperShift
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.indexes
  - content.code.annotate
plugins:
- search
- mermaid2
- glightbox:
    touchNavigation: true
    loop: false
    effect: zoom
    width: 100%
    height: auto
    zoomable: true
    draggable: true
    skip_classes:
      - custom-skip-class-name
    auto_caption: false
    caption_position: bottom
docs_dir: content
repo_url: https://github.com/openshift/hypershift
edit_uri: edit/main/docs/content
repo_name: openshift/hypershift
extra_javascript:
  - https://unpkg.com/mermaid@9.2.2/dist/mermaid.min.js
markdown_extensions:
- toc:
    toc_depth: "2-3"
- attr_list:
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.superfences:
    # make exceptions to highlighting of code:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:mermaid2.fence_mermaid
- pymdownx.snippets
- admonition
- pymdownx.details
- pymdownx.tabbed:
    alternate_style: true
nav:
- Home: index.md
- 'Getting started': getting-started.md
- 'How-to guides':
  - how-to/index.md
  - how-to/cluster-configuration.md
  - how-to/distribute-hosted-cluster-workloads.md
  - how-to/upgrades.md
  - how-to/restart-control-plane-components.md
  - how-to/pause-reconciliation.md
  - how-to/debug-nodes.md
  - how-to/metrics-sets.md
  - 'Automated Machine Management':
    - how-to/automated-machine-management/index.md
    - how-to/automated-machine-management/scale-to-zero-dataplane.md
    - how-to/automated-machine-management/nodepool-upgrades.md
    - how-to/automated-machine-management/node-tuning.md
  - "AWS":
    - how-to/aws/create-infra-iam-separately.md
    - how-to/aws/create-aws-hosted-cluster-multiple-zones.md
    - how-to/aws/deploy-aws-private-clusters.md
    - how-to/aws/external-dns.md
    - how-to/aws/etc-backup-restore.md
    - how-to/aws/disaster-recovery.md
    - how-to/aws/troubleshooting.md
  - 'Azure':
    - how-to/azure/create-azure-cluster.md
  - 'Agent':
    - how-to/agent/create-agent-cluster.md
  - 'Kubevirt':
    - how-to/kubevirt/create-kubevirt-cluster.md
  - 'None':
    - how-to/none/create-none-cluster.md
  - 'PowerVS':
    - how-to/powervs/create-cluster-powervs.md
    - how-to/powervs/create-infra-separately.md
    - how-to/powervs/prerequisites-and-env-guide.md
- 'Reference':
  - reference/index.md
  - reference/goals-and-design-invariants.md
  - reference/api.md
  - "Infrastructure":
    - "AWS": reference/infrastructure/aws.md
  - reference/concepts-and-personas.md
  - reference/controller-architecture.md
  - reference/multi-platform-support.md
  - reference/versioning-support.md
  - reference/SLOs.md
- 'Contribute':
  - contribute/index.md
  - contribute/release-process.md
  - contribute/develop-in-cluster.md
  - contribute/custom-images.md
  - contribute/onboard-a-platform.md
  - contribute/run-tests.md
  - contribute/contribute-docs.md
