site_name: HyperShift
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.indexes
  - content.code.annotate
plugins:
- search
- mermaid2:
    version: 11.2.0
- glightbox:
    touchNavigation: true
    loop: false
    effect: zoom
    width: 100%
    height: auto
    zoomable: true
    draggable: true
    skip_classes:
      - custom-skip-class-name
    auto_caption: false
    caption_position: bottom
docs_dir: content
repo_url: https://github.com/openshift/hypershift
edit_uri: edit/main/docs/content
repo_name: openshift/hypershift
extra_javascript:
  - https://unpkg.com/mermaid@11.2.0/dist/mermaid.min.js
markdown_extensions:
- toc:
    toc_depth: "2-3"
- attr_list:
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.superfences:
    # make exceptions to highlighting of code:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:mermaid2.fence_mermaid
- pymdownx.snippets
- admonition
- pymdownx.details
- pymdownx.tabbed:
    alternate_style: true
validation:
  omitted_files: warn
  absolute_links: ignore  # Or 'relative_to_docs' - new in MkDocs 1.6
  unrecognized_links: ignore
  anchors: ignore
  nav:
    omitted_files: ignore
nav:
- Home: index.md
- 'Getting started': getting-started.md
- 'How-to guides':
  - how-to/index.md
  - how-to/feature-gates.md
  - how-to/cluster-configuration.md
  - how-to/distribute-hosted-cluster-workloads.md
  - how-to/upgrades.md
  - how-to/restart-control-plane-components.md
  - how-to/pause-reconciliation.md
  - how-to/per-hostedcluster-dashboard.md
  - how-to/metrics-sets.md
  - how-to/troubleshooting-general.md
  - 'Common':
    - how-to/common/exposing-services-from-hcp.md
    - how-to/common/multi-arch-on-hcp.md
  - 'HyperShift Operator Install':
    - how-to/install/index.md
  - 'Disaster Recovery':
    - how-to/disaster-recovery/index.md
    - how-to/disaster-recovery/backup-and-restore-oadp.md
    - how-to/disaster-recovery/etcd-recovery.md
  - 'Automated Machine Management':
    - how-to/automated-machine-management/index.md
    - how-to/automated-machine-management/scale-to-zero-dataplane.md
    - how-to/automated-machine-management/nodepool-lifecycle.md
    - how-to/automated-machine-management/node-tuning.md
    - how-to/automated-machine-management/configure-machines.md
    - how-to/automated-machine-management/performance-profiling.md
  - 'AWS':
    - how-to/aws/create-aws-hosted-cluster-arm-workers.md
    - how-to/aws/create-infra-iam-separately.md
    - how-to/aws/create-aws-hosted-cluster-multiple-zones.md
    - how-to/aws/deploy-aws-private-clusters.md
    - how-to/aws/external-dns.md
    - how-to/aws/etc-backup-restore.md
    - how-to/aws/disaster-recovery.md
    - how-to/aws/shared-vpc.md
    - how-to/aws/define-custom-kube-api-name.md
    - 'Other SDN providers': how-to/aws/other-sdn-providers.md
    - 'Troubleshooting':
        - how-to/aws/troubleshooting/index.md
        - how-to/aws/troubleshooting/debug-nodes.md
        - how-to/aws/troubleshooting/troubleshooting-disaster-recovery.md
  - 'Azure':
    - how-to/azure/create-azure-cluster-with-options.md
    - how-to/azure/create-azure-cluster_on_aks.md
    - how-to/azure/scheduler.md
    - 'Troubleshooting':
        - how-to/azure/troubleshooting/index.md
        - how-to/azure/troubleshooting/debug-nodes.md
  - 'Agent':
    - how-to/agent/create-agent-cluster.md
    - how-to/agent/create-heterogeneous-nodepools.md
    - 'Other SDN providers': how-to/agent/other-sdn-providers.md
    - 'Exposing HCP Services': how-to/agent/exposing-services-from-hcp.md
  - 'Disconnected':
    - how-to/disconnected/index.md
    - how-to/disconnected/tls-certificates.md
    - 'IDMS/ICSP Config for Management Cluster': how-to/disconnected/idms-icsp-for-management-clusters.md
    - how-to/disconnected/image-content-sources.md
    - how-to/disconnected/disconnected-workarounds.md
    - how-to/disconnected/known-issues.md
  - 'Kubevirt':
    - how-to/kubevirt/create-kubevirt-cluster.md
    - how-to/kubevirt/ingress-and-dns.md
    - how-to/kubevirt/configuring-storage.md
    - how-to/kubevirt/configuring-network.md
    - how-to/kubevirt/performance-tuning.md
    - how-to/kubevirt/external-infrastructure.md
    - how-to/kubevirt/gpu-devices.md
    - how-to/kubevirt/troubleshooting-kubevirt-cluster.md
  - 'OpenStack':
    - how-to/openstack/index.md
    - how-to/openstack/prerequisites.md
    - how-to/openstack/hostedcluster.md
    - how-to/openstack/az.md
    - how-to/openstack/additional-ports.md
    - how-to/openstack/performance-tuning.md
    - how-to/openstack/destroy.md
  - 'None':
    - how-to/none/create-none-cluster.md
    - 'Exposing HCP Services': how-to/agent/exposing-services-from-hcp.md
  - 'PowerVS':
    - how-to/powervs/create-cluster-powervs.md
    - how-to/powervs/create-infra-separately.md
    - how-to/powervs/prerequisites-and-env-guide.md
- 'Self-Managed Laboratories':
  - 'MultiCluster Engine and Agent provider':
    - labs/index.md
    - 'IPv4':
      - labs/IPv4/index.md
      - 'Hypervisor':
        - labs/IPv4/hypervisor/index.md
        - 'Bare Metal Requisites': labs/IPv4/hypervisor/requisites.md
        - 'Packaging': labs/IPv4/hypervisor/packaging.md
        - 'Network Manager Dispatcher': labs/IPv4/hypervisor/network-manager-dispatcher.md
        - 'BMC Access for Metal3': labs/IPv4/hypervisor/redfish-for-vms.md
        - labs/IPv4/hypervisor/hypervisor-system-config.md
      - labs/IPv4/dns.md
      - labs/IPv4/registry.md
      - 'Management Cluster':
        - 'Management Cluster Provisioning': labs/IPv4/mgmt-cluster/index.md
        - 'Networking': labs/IPv4/mgmt-cluster/network.md
        - 'Openshift Compact IPv4': labs/IPv4/mgmt-cluster/compact-ipv4.md
      - labs/IPv4/webserver.md
      - 'Mirroring and Image Content Sources':
        - labs/IPv4/mirror/index.md
        - 'Mirroring': labs/IPv4/mirror/mirroring.md
        - 'Image Content Policies': labs/IPv4/mirror/ICSP-IDMS.md
      - 'Multicluster Engine':
        - 'Multicluster Engine': labs/IPv4/mce/index.md
        - 'ACM/MCE Deployment': labs/IPv4/mce/multicluster-engine.md
        - 'Agent Service Config': labs/IPv4/mce/agentserviceconfig.md
      - 'TLS Certificates': labs/IPv4/tls-certificates.md
      - 'HostedCluster':
        - 'Hosted Cluster Creation': labs/IPv4/hostedcluster/index.md
        - 'Hosted Cluster Object': labs/IPv4/hostedcluster/hostedcluster.md
        - 'Node Pools': labs/IPv4/hostedcluster/nodepool.md
        - 'Infra Env': labs/IPv4/hostedcluster/infraenv.md
        - 'Worker Nodes': labs/IPv4/hostedcluster/worker-nodes.md
        - 'Bare Metal Hosts': labs/IPv4/hostedcluster/baremetalhost.md
      - 'Finishing Deployment':
        - labs/IPv4/watching/index.md
        - 'Watching the Control Plane': labs/IPv4/watching/watching-cp.md
        - 'Watching the Data Plane': labs/IPv4/watching/watching-dp.md
    - 'IPv6':
      - labs/IPv6/index.md
      - 'Hypervisor':
        - labs/IPv6/hypervisor/index.md
        - 'Bare Metal Requisites': labs/IPv6/hypervisor/requisites.md
        - 'Packaging': labs/IPv6/hypervisor/packaging.md
        - 'Network Manager Dispatcher': labs/IPv6/hypervisor/network-manager-dispatcher.md
        - 'BMC Access for Metal3': labs/IPv6/hypervisor/redfish-for-vms.md
        - labs/IPv6/hypervisor/hypervisor-system-config.md
      - labs/IPv6/dns.md
      - labs/IPv6/registry.md
      - 'Management Cluster':
        - 'Management Cluster Provisioning': labs/IPv6/mgmt-cluster/index.md
        - 'Networking': labs/IPv6/mgmt-cluster/network.md
        - 'Openshift Compact IPv6': labs/IPv6/mgmt-cluster/compact-ipv6.md
      - labs/IPv6/webserver.md
      - 'Mirroring and Image Content Sources':
        - labs/IPv6/mirror/index.md
        - 'Mirroring': labs/IPv6/mirror/mirroring.md
        - 'Image Content Policies': labs/IPv6/mirror/ICSP-IDMS.md
      - 'Multicluster Engine':
        - 'Multicluster Engine': labs/IPv6/mce/index.md
        - 'ACM/MCE Deployment': labs/IPv6/mce/multicluster-engine.md
        - 'Agent Service Config': labs/IPv6/mce/agentserviceconfig.md
      - 'TLS Certificates': labs/IPv6/tls-certificates.md
      - 'HostedCluster':
        - 'Hosted Cluster Creation': labs/IPv6/hostedcluster/index.md
        - 'Hosted Cluster Object': labs/IPv6/hostedcluster/hostedcluster.md
        - 'Node Pools': labs/IPv6/hostedcluster/nodepool.md
        - 'Infra Env': labs/IPv6/hostedcluster/infraenv.md
        - 'Worker Nodes': labs/IPv6/hostedcluster/worker-nodes.md
        - 'Bare Metal Hosts': labs/IPv6/hostedcluster/baremetalhost.md
      - 'Finishing Deployment':
        - labs/IPv6/watching/index.md
        - 'Watching the Control Plane': labs/IPv6/watching/watching-cp.md
        - 'Watching the Data Plane': labs/IPv6/watching/watching-dp.md
    - 'Dual Stack':
      - labs/Dual/index.md
      - 'Hypervisor':
        - labs/Dual/hypervisor/index.md
        - 'Bare Metal Requisites': labs/Dual/hypervisor/requisites.md
        - 'Packaging': labs/Dual/hypervisor/packaging.md
        - 'Network Manager Dispatcher': labs/Dual/hypervisor/network-manager-dispatcher.md
        - 'BMC Access for Metal3': labs/Dual/hypervisor/redfish-for-vms.md
        - labs/Dual/hypervisor/hypervisor-system-config.md
      - labs/Dual/dns.md
      - labs/Dual/registry.md
      - 'Management Cluster':
        - 'Management Cluster Provisioning': labs/Dual/mgmt-cluster/index.md
        - 'Networking': labs/Dual/mgmt-cluster/network.md
        - 'Openshift Compact Dual': labs/Dual/mgmt-cluster/compact-dual.md
      - labs/Dual/webserver.md
      - 'Mirroring and Image Content Sources':
        - labs/Dual/mirror/index.md
        - 'Mirroring': labs/Dual/mirror/mirroring.md
        - 'Image Content Policies': labs/Dual/mirror/ICSP-IDMS.md
      - 'Multicluster Engine':
        - 'Multicluster Engine': labs/Dual/mce/index.md
        - 'ACM/MCE Deployment': labs/Dual/mce/multicluster-engine.md
        - 'Agent Service Config': labs/Dual/mce/agentserviceconfig.md
      - 'TLS Certificates': labs/Dual/tls-certificates.md
      - 'HostedCluster':
        - 'Hosted Cluster Creation': labs/Dual/hostedcluster/index.md
        - 'Hosted Cluster Object': labs/Dual/hostedcluster/hostedcluster.md
        - 'Node Pools': labs/Dual/hostedcluster/nodepool.md
        - 'Infra Env': labs/Dual/hostedcluster/infraenv.md
        - 'Worker Nodes': labs/Dual/hostedcluster/worker-nodes.md
        - 'Bare Metal Hosts': labs/Dual/hostedcluster/baremetalhost.md
      - 'Finishing Deployment':
        - labs/Dual/watching/index.md
        - 'Watching the Control Plane': labs/Dual/watching/watching-cp.md
        - 'Watching the Data Plane': labs/Dual/watching/watching-dp.md
- 'Recipes':
  - recipes/index.md
  - 'Common':
    - 'Expose Data Plane Ingress via MetalLB': recipes/common/exposing-dataplane-with-metallb.md
    - 'Replace the default CRI-O runtime': recipes/common/replace-crio-runtime.md
- 'Reference':
  - reference/index.md
  - reference/goals-and-design-invariants.md
  - reference/api.md
  - reference/konnectivity.md
  - "Infrastructure":
    - reference/infrastructure/index.md
    - "AWS": reference/infrastructure/aws.md
    - "Agent": reference/infrastructure/agent.md
  - 'Architecture':
    - reference/architecture/index.md
    - 'Multicluster Engine and Agent': reference/architecture/mce-and-agent.md
    - 'Shared Ingress in Azure Red Hat OpenShift': reference/aro/shared-ingress.md
  - 'Manifests':
    - reference/manifests/index.md
    - 'IBM Cloud':
      - '4.9': reference/manifests/ibmcloud/4.9.md
      - '4.10': reference/manifests/ibmcloud/4.10.md
      - '4.11': reference/manifests/ibmcloud/4.11.md
      - '4.12': reference/manifests/ibmcloud/4.12.md
      - '4.13': reference/manifests/ibmcloud/4.13.md
  - 'Openshift behaviour deviations':
    - reference/ocp-behaviour-deviations/index.md
    - 'Upgrade 4.17 > 4.18': reference/ocp-behaviour-deviations/upgrade-4.17-4.18.md
  - reference/concepts-and-personas.md
  - reference/controller-architecture.md
  - reference/multi-platform-support.md
  - reference/versioning-support.md
  - reference/SLOs.md
- 'Contribute':
  - contribute/index.md
  - 'Release Process': contribute/release-process.md
  - 'Custom Images': contribute/custom-images.md
  - 'Onboard a Platform': contribute/onboard-a-platform.md
  - 'Run Tests': contribute/run-tests.md
  - 'Develop in Cluster': contribute/develop_in_cluster.md
  - 'Run hypershift-operator locally': contribute/run-hypershift-operator-locally.md
  - 'Contribute to docs': contribute/contribute-docs.md
